name: Generate Final Document

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      # Installation des outils nécessaires
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          gem install asciidoctor
          gem install asciidoctor-pdf
          gem install rouge

      # Préparation et Exécution des scripts
      - name: Run Scripts
        run: |
          dos2unix initialize_project.sh
          dos2unix generate_final_document.sh
          
          chmod +x initialize_project.sh
          chmod +x generate_final_document.sh
          
          echo "=== EXÉCUTION DE L'INITIALISATION ==="
          ./initialize_project.sh
          
          echo "=== EXÉCUTION DE LA GÉNÉRATION ==="
          ./generate_final_document.sh

          echo "=== VERIFICATION FICHIERS ==="
          find . -name "*.pdf"

      # Sauvegarde du PDF
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Final-Document-PDF
          path: "**/*.pdf"
          retention-days: 5
          if-no-files-found: error
