name: Generate Final Document

# Déclenchement MANUEL uniquement (Bouton "Run workflow")
on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installation de l'environnement Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      # 3. Installation des outils AsciiDoc
      - name: Install Asciidoctor & PDF extensions
        run: |
          gem install asciidoctor
          gem install asciidoctor-pdf
          gem install rouge

      # 4. Exécution du script de génération
      - name: Run Generation Script
        run: |
          chmod +x generate_final_document.sh
          ./generate_final_document.sh

      # 5. Sauvegarde du PDF généré
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Final-Document-PDF
          path: "*.pdf"
          retention-days: 5
